# Generated by Django 5.0.3 on 2024-04-03 13:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('d_phone', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'enter 10 digits')])),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')])),
                ('language', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')])),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('paper_name',),
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')])),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'enter 6 digits')])),
                ('phone', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'enter 10 digits')])),
                ('due', models.FloatField(default=0)),
                ('subscription', models.ManyToManyField(default='', to='newspaper_agency.publications')),
            ],
        ),
        migrations.CreateModel(
            name='Subscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('subscription', models.ManyToManyField(default='', to='newspaper_agency.publications')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_agency.customers')),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_agency.distributors')),
            ],
        ),
        migrations.CreateModel(
            name='WithHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_agency.customers')),
            ],
        ),
    ]
